# Generated by Django 3.1.7 on 2021-03-17 13:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_subscriber',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Подписчик категории'),
        ),
        migrations.DeleteModel(
            name='PostCategory',
        ),
    ]
