# Generated by Django 3.1.7 on 2021-03-19 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20210319_1538'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='author',
            new_name='author_user',
        ),
    ]
