# Generated by Django 3.1.7 on 2021-03-20 20:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0004_auto_20210319_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_subscriber',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='Подписчик категории'),
        ),
        migrations.AlterField(
            model_name='post',
            name='article_author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='news.author', verbose_name='Автор статьи или новости'),
        ),
    ]
